# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import langchain_service_pb2 as langchain__service__pb2


class LangChainServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateResponse = channel.unary_unary(
                '/langchain.LangChainService/GenerateResponse',
                request_serializer=langchain__service__pb2.QueryRequest.SerializeToString,
                response_deserializer=langchain__service__pb2.QueryResponse.FromString,
                )


class LangChainServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateResponse(self, request, context):
        """A simple API to generate a response based on a user's query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LangChainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateResponse,
                    request_deserializer=langchain__service__pb2.QueryRequest.FromString,
                    response_serializer=langchain__service__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'langchain.LangChainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LangChainService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/langchain.LangChainService/GenerateResponse',
            langchain__service__pb2.QueryRequest.SerializeToString,
            langchain__service__pb2.QueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
