# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'llm_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11llm_service.proto\x12\x03llm\"!\n\x0bTextRequest\x12\x12\n\ninput_text\x18\x01 \x01(\t\"&\n\x0cTextResponse\x12\x16\n\x0egenerated_text\x18\x01 \x01(\t\"\x14\n\x12HealthCheckRequest\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x85\x01\n\nLLMService\x12\x35\n\x0cGenerateText\x12\x10.llm.TextRequest\x1a\x11.llm.TextResponse0\x01\x12@\n\x0bHealthCheck\x12\x17.llm.HealthCheckRequest\x1a\x18.llm.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=26
  _globals['_TEXTREQUEST']._serialized_end=59
  _globals['_TEXTRESPONSE']._serialized_start=61
  _globals['_TEXTRESPONSE']._serialized_end=99
  _globals['_HEALTHCHECKREQUEST']._serialized_start=101
  _globals['_HEALTHCHECKREQUEST']._serialized_end=121
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=123
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=160
  _globals['_LLMSERVICE']._serialized_start=163
  _globals['_LLMSERVICE']._serialized_end=296
# @@protoc_insertion_point(module_scope)
